spring.application.name=Bio_Backend
# === Config PostgreSQL - a copier/adapter dans src/main/resources/application.properties ===

spring.datasource.url=jdbc:postgresql://localhost:5432/bioconversion_db
spring.datasource.username=postgres
spring.datasource.password=2000@
spring.datasource.driver-class-name=org.postgresql.Driver

# ddl-auto=update : Hibernate cree/adapte les tables automatiquement
# a partir des entites @Entity. Pratique en developpement.
# ATTENTION : ne JAMAIS utiliser "update" ou "create" en production,
# utiliser plutot un outil de migration (Flyway/Liquibase) plus tard.
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
